### ISSUE TITLE
Problem with plugin on Apex 5.1

### ISSUE THREAD

**Issue by ids245** [foobarbaz-pl/apex-plugin-floating-scrollbar#9] opened 2017-03-16 17:32 UTC
Good afternoon. I tested the plug-in on Apex 5.1 Interactive Report and Grid Report following the instructions made the settings, but the scrollbar did not appear. Tell me please, what could be the problem?

-------
Dynamic Action
Name = My_Dynamic_Action_Name
Sequence = 20
Event = After Refresh
Selection Type = Region
Region = My_Region_Name

-------
Action Properties
Action = Floating Scrollbar (Plug-In)
Region = My_Region_Name
Sequence = 10
Event = My_Dynamic_Action_Name
Fire When Result Is = True

**Comment by foobarbaz-pl** [comment] 2017-03-16 20:45
I haven't tested this plugin with interactive grid, most probably it won't work.
With interactive report you might get into troubles if you are using region template other than interactive report. I'm planning to add a parameter for custom jQuery selector to tackle such cases.

**Comment by ids245** [comment] 2017-03-31 06:51
Thank you. We are waiting for a new update.

**Comment by foobarbaz-pl** [comment] 2017-09-26 12:32
Duplicate of #7

**Closed as completed by foobarbaz-pl** 2017-09-26 12:32 UTC
Labels: duplicate
